### ISSUE TITLE
alt command buttons

### ISSUE THREAD

**Issue by remi-grumeau** [johnrobinsn/goo.js#1]
This might be happen only on OSX, but it fires a Goo mousemove event too when i press the following keys:
- cmd
- alt
- ctrl
- fn
- shift
- capslock
- f3 (exposé)

**Comment by johnrobinsn** [comment]
Thanks... I'm not seeing that... What browser and with a particular sample or your own code (can you provide an example)?

**Comment by remi-grumeau** [comment]
Here is a video that shows it http://cl.ly/3K2z1Z312r2X
I only move the mouse on the first 2 seconds

**Comment by johnrobinsn** [comment]
Thanks Remi.

This appears to be a bug with Safari.  I've seen a couple of threads mentioning same... http://stackoverflow.com/questions/2612907/webkit-and-safari-fire-mousemove-even-when-mouse-doesnt-move

I have submitted a workaround that seems to work well for me.  Let me know how it works for you.
